### ISSUE TITLE
read_sf2.py中出现了NameError：name'current_decay'is not defined，求助

### ISSUE THREAD

**Issue by ferry-hhh** [Rainbow-Dreamer/sf2_loader#13]
在sf2_loader/read_sf2/read_sf2.py的773行，出现了NameError：name'current_decay'is not defined错误，作者大大有什么解决方案嘛？

**Comment by ferry-hhh** [comment]
sf2_loader==0.94的版本有上述问题，目前的版本貌似已经修复了，作者大大威武！

**Comment by Rainbow-Dreamer** [comment]
这个是之前的版本的一个bug，几天前更新版本时已经修复了，现在更新到最新版本就没问题了

**Comment by Rainbow-Dreamer** [comment]
不客气，感谢支持
