### ISSUE TITLE
OSError: /lib/x86_64-linux-gnu/libwayland-server.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0

### ISSUE THREAD

**Issue by Irislucent** [Rainbow-Dreamer/sf2_loader#15]
I got this error when trying to initialize a loader. Python version == 3.9.2. What could have happened? Thanks!

**Comment by Rainbow-Dreamer** [comment]
It seems that this error is caused by uncompatible Linux distros, this package is not ensured to work on all Linux distros, you can try Ubuntu 18.04.5 which has been fully tested.
