### ISSUE TITLE
Export Piece fails: "AttributeError: module 'fluidsynth' has no attribute 'Synth'"

### ISSUE THREAD

**Issue by gildurao** [Rainbow-Dreamer/sf2_loader#2]
Hello again 👋 ,

I was trying to export a piece with the following code:

```python
import sf2_loader as sf
import pathlib

scriptDirectory = pathlib.Path(__file__).parent.resolve()
filePath = scriptDirectory / 'Cello2.sf2'

guitar = (sf.mp.C('CM7', 4, 1/4, 1/8) ^ 2 | sf.mp.C('G7sus', 3, 1/4, 1/8) ^ 2
          | sf.mp.C('A7sus', 3, 1/4, 1/8) ^ 2 | sf.mp.C('Em7', 3, 1/4, 1/8) ^ 2 |
          sf.mp.C('FM7', 3, 1/4, 1/8) ^ 2 | sf.mp.C('CM7', 4, 1/4, 1/8)@1 |
          sf.mp.C('AbM7', 3, 1/4, 1/8) ^ 2 | sf.mp.C('G7sus', 3, 1/4, 1/8) ^ 2)

guitar.tempo = 60

sf2.export_piece(guitar, name="piece_example.wav")
```

Before I got to the error that I wrote on the title, I had to change line 550 in ``read_sf2.py`` and declare the ```tempo``` property of my ``guitar``  object.

from 

```python
current_chord.normalize_tempo()
```

to

```python
current_chord.normalize_tempo(bpm)
```

Otherwise, these errors would be thrown:

```
  File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\site-packages\sf2_loader\read_sf2\read_sf2.py", line 549, in export_piece
    bpm = current_chord.tempo
AttributeError: 'chord' object has no attribute 'tempo'
```

```
  File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\site-packages\sf2_loader\read_sf2\read_sf2.py", line 550, in export_piece
    current_chord.normalize_tempo()
TypeError: normalize_tempo() missing 1 required positional argument: 'bpm'
```

After fixing those, and running my script, I get this:

```
  File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\site-packages\sf2_loader\read_sf2\read_sf2.py", line 181, in __init__
    self.synth = fluidsynth.Synth()
AttributeError: module 'fluidsynth' has no attribute 'Synth'
```

Python version: 3.9.5
fluidsynth version: 0.2

Was hoping you could guide me to what's missing here

**Comment by Rainbow-Dreamer** [comment]
Is this on Linux or Windows? If it is on Linux, compatible version of this package has not come out yet.

**Comment by gildurao** [comment]
It's on Windows. I'm guessing this is happening because I did not install the actual FluidSynth program?

**Comment by Rainbow-Dreamer** [comment]
No, this package actually ships all of the required fluidsynth dlls in it for Windows, so you don't need to install fluidsynth.

**Comment by gildurao** [comment]
I noticed there's a fluidsynth and pyFluidSynth packages. Which one should I be using?

**Comment by Rainbow-Dreamer** [comment]
This package uses both of them, to be more clear, it uses pyfluidsynth which uses fluid synth.

**Comment by Rainbow-Dreamer** [comment]
You don’t need to reinstall python, it is not a python version problem actually.

**Comment by Rainbow-Dreamer** [comment]
you can try to uninstall and reinstall this package again, before reinstall, make sure to delete all of the sf2_loader folder in site-packages.

**Comment by gildurao** [comment]
Reinstalled the package, but still have the fluidsynth issue

**Comment by Rainbow-Dreamer** [comment]
Could you try to export a note or a chord first to see if this issue still happens?

**Comment by gildurao** [comment]
Export note does not reproduce the issue. I think the issue only appears when I change read_sf2.py, line 550

from

```python
current_chord.normalize_tempo()
```
to

```python
current_chord.normalize_tempo(bpm)
```

Because if I don't do that change, this is the error that I get when exporting piece

```
  File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\site-packages\sf2_loader\read_sf2\read_sf2.py", line 550, in export_piece
    current_chord.normalize_tempo()
TypeError: normalize_tempo() missing 1 required positional argument: 'bpm'
```

**Comment by gildurao** [comment]
I just ran ```pip list``` and I don't see the fluidsynth package. Is this expected?

```
Package     Version
----------- -------
autopep8    1.5.7
MIDIUtil    1.2.1
mido        1.2.10
musicpy     3.39
numpy       1.21.2
Pillow      8.3.2
pip         21.2.4
pycodestyle 2.7.0
pydub       0.25.1
pygame      2.0.1
pyglet      1.5.11
setuptools  57.4.0
sf2-loader  0.32
simpleaudio 1.0.4
toml        0.10.2
wheel       0.37.0
```

**Comment by Rainbow-Dreamer** [comment]
Yeah, so this is the musical syntax issue you code is showing which I will talk about. To be short, the guitar you make is a chord instance, not a piece instance, so you can only use export_chord function to export it. To construct a piece instance, there are independent syntax for it, you can refer to musicpy wiki. And for the install list, yes, it is expected, since fluidsynth itself is not a python package, it is compiled C/C++ project.

**Comment by gildurao** [comment]
Ok, I tried using the code found in https://github.com/Rainbow-Dreamer/musicpy/wiki/Basic-syntax-of-musicpy-Part-3

```python
new_piece = piece([A, B, C, D],
                  ['Acoustic Grand Piano', 'Electric Bass (finger)', 'Orchestral Harp', 'Synth Drum'],
                  150,
                  [0, 2, 2, 4],
                  ['piano', 'bass', 'harp', 'drum'])
```

replaced it with

```python
new_piece = sf.mp.piece([sf.mp.A, sf.mp.B, sf.mp.C, sf.mp.D],
                        ['Acoustic Grand Piano',
                         'Electric Bass (finger)', 'Orchestral Harp', 'Synth Drum'],
                        150,
                        [0, 2, 2, 4],
                        ['piano', 'bass', 'harp', 'drum'])
```

but get the error:

```
Traceback (most recent call last):
  File "C:\Users\GilDurao\Documents\GitHub\flutterpy-lmusic\flutterpy_lmusic\lib\yourscript.py", line 19, in <module>
    new_piece = sf.mp.piece([sf.mp.A, sf.mp.B, sf.mp.C, sf.mp.D],
AttributeError: module 'musicpy.musicpy' has no attribute 'A'
```

Is the wiki outdated? Could you provide a quick example of a working piece object?

**Comment by Rainbow-Dreamer** [comment]
here A B C D are just some variables of chord instances, which are not defined here, you can assign them to some chords. I will provide a working piece example code for you to export after I finished my current stuffs.

**Comment by gildurao** [comment]
Ok, I managed to export a piece and hear it using a sample from https://github.com/Rainbow-Dreamer/musicpy/wiki/musicpy-composition-code-examples-part-2

Off to read your wiki and learn more about musicpy. Thanks again for your help! Closing the issue.

**Comment by Rainbow-Dreamer** [comment]
Good to hear that :)
