### ISSUE TITLE
Exporting musicpy piece fails [possibly not an issue with library, but syntax error of musicpy]

### ISSUE THREAD

**Issue by gildurao** [Rainbow-Dreamer/sf2_loader#4]
Hello again :wave: ,

I've been following musicpy's documentation, and from what I understood a ``chord`` can also represent a whole piece of music. I was trying to understand this by creating a simple example by just creating a piece that is a C chord over 3 bars:

```python
c = sf.mp.note('C', 5, 1, 100)
e = sf.mp.note('E', 5, 1, 100)
g = sf.mp.note('G', 5, 1, 100)

myGChord = sf.mp.chord([c, e, g])

fantasyInG = sf.mp.piece([myGChord], [1], 100, [0], channels=[1])
```

This code runs fine, but when I export the piece:

```python
sf2.export_piece(fantasyInG, "fantasy_in_g.wav")
```

the following error is output:

```
Traceback (most recent call last):
  File "yourscript.py", line 51, in <module>
    sf2.export_piece(fantasyInG, "fantasy_in_g.wav")
  File "/usr/local/lib/python3.8/dist-packages/sf2_loader/read_sf2/read_sf2.py", line 583, in export_piece
    current_audio = self.export_chord(each, decay, track, 0,
  File "/usr/local/lib/python3.8/dist-packages/sf2_loader/read_sf2/read_sf2.py", line 432, in export_chord
    whole_length_with_decay = mp.chord(temp.notes, [
  File "/usr/local/lib/python3.8/dist-packages/sf2_loader/read_sf2/read_sf2.py", line 433, in <listcomp>
    temp.notes[i].duration + current_decay[i]
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

So, I was wondering where my mistake is syntax wise, because I'm certain that this is just my lack of knowledge of musicpy :sweat_smile:

**Comment by Rainbow-Dreamer** [comment]
Well, I forgot one important thing, the codes for Linux and macOS compatible versions are partly changed for compatibility, so it is actually necessary to download them from release page and run python setup.py install to install this package, otherwise some of the functionalities won't functioning normally on Linux and macOS.

**Comment by Rainbow-Dreamer** [comment]
For your current issue, it is just a wrong use of parameters, the second parameters of `export_piece` function is decay time, you take it as the export file name, which causes the errors.

**Comment by gildurao** [comment]
Silly me, I forgot to add "name=" :smile: thank you!

**Comment by Rainbow-Dreamer** [comment]
You're welcome :) By the way, you actually don't need to construct a C major chord like this in musicpy, there are many advanced syntax for building complex chords in musicpy, you will see them in basic syntax sections of the wiki.
Here I will provide 2 ways of constructing a C major chord using musicpy as examples:
```python
# using chord name
myGChord = sf.mp.C('C', 5, duration=1, volume=100)
# construct a C major chord starts at C5 with all notes have duration of 1 bar and volume of 100
myGChord = sf.mp.C('Cmaj7', 5, duration=1, volume=100) # build a Cmaj7 chord

# using a string of notes
myGChord = sf.mp.chord('C5, E5, G5', duration=1, volume=100)
myGChord = sf.mp.chord('c5, e5, g5', duration=1, volume=100) # the note names could also be lowercase
myGChord = sf.mp.chord('C, E, G', duration=1, volume=100) # if no octave numbers are specified,
# then it will automatically builds up with smallest intervals possible
myGChord = sf.mp.chord('C5[1;0;100], E5[1;0;100], G5[1;0;100]') # this is an advanced syntax,
# I also recommend "translate" syntax which is even more convenient than this

# using a list of notes (could be note instances or strings representing notes)
myGChord = sf.mp.chord(['C5', 'E5', 'G5'], duration=1, volume=100)
myGChord = sf.mp.chord([sf.mp.N('C5'), sf.mp.N('E5'), sf.mp.N('G5')], duration=1, volume=100)
```

**Comment by Rainbow-Dreamer** [comment]
If you have encountered any syntax issues of musicpy, just ask here.
