### ISSUE TITLE
'ModuleNotFoundError: No module named fluidsynth'

### ISSUE THREAD

**Issue by gildurao** [Rainbow-Dreamer/sf2_loader#7]
Hello,

After upgrading to most recent version, I get this error when trying to run any script that improts sf2_loader

```
 File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\site-packages\sf2_loader\__init__.py", line 2, in <module>
    from .read_sf2.read_sf2 import *
  File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\site-packages\sf2_loader\read_sf2\read_sf2.py", line 4, in <module>      
    import fluidsynth
ModuleNotFoundError: No module named 'fluidsynth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GilDurao\Documents\GitHub\flutterpy-lmusic\flutterpy_lmusic\lib\yourscript.py", line 2, in <module>
    import sf2_loader as sf
  File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\site-packages\sf2_loader\__init__.py", line 4, in <module>
    from .read_sf2_32bit.read_sf2 import *
  File "C:\Users\GilDurao\AppData\Local\Programs\Python\Python39\lib\site-packages\sf2_loader\read_sf2_32bit\read_sf2.py", line 4, in <module>
    import fluidsynth
ModuleNotFoundError: No module named 'fluidsynth'
```

I'm not really sure why this happens, because in the sf2_loader folders there is indeed a module named ```fluidsynth.py```

**Comment by Rainbow-Dreamer** [comment]
I see it goes to read_sf2_32bit folder as your are using a 64-bit python version, this is because when sf2_loader is importing, it will firstly try to import 64bit version of sf2_lodaer, and if there are import errors, it will try 32bit version. Now I think we need to check what exactly is the import errors when importing sf2_loader 64-bit version. Could you try to change the content in `__init__.py` to just simply a line `from .read_sf2.read_sf2 import *` ?

**Comment by gildurao** [comment]
> I see it goes to read_sf2_32bit folder as your are using a 64-bit python version, this is because when sf2_loader is importing, it will firstly try to import 64bit version of sf2_loader, and if there are import errors, it will try 32bit version. Now I think we need to check what exactly is the import errors when importing sf2_loader 64-bit version. Could you try to change the content in `__init__.py` to just simply a line `from .read_sf2.read_sf2 import *` and run again to see what the errors you get? Thanks.

I reinstalled Python and installed sf2_loader and it started working again... I'm not sure what was wrong or what I did.

**Comment by gildurao** [comment]
The issue has appeared again, out of nowhere 😐

**Comment by Rainbow-Dreamer** [comment]
Could you show the files under sf2_loader in python site-packages (including the 2 read_sf2 folders)?

**Comment by Rainbow-Dreamer** [comment]
But in the past you are using v0.32 and did not get any errors from importing?

**Comment by gildurao** [comment]
> Do you have multiple python versions paths in your system environment variables now?

No, I do not.

**Comment by Rainbow-Dreamer** [comment]
I will figure this out, because on my computer this error does not appear from anywhere, it is possible you have some python packages that conflicts with the `import fluidsynth`, but since you said that you reinstalled python, I think this is not the case.

**Comment by gildurao** [comment]
Seems to be working now!

**Comment by Rainbow-Dreamer** [comment]
That's great! If you encounter this problem again, please let me know. Thanks :)
